model:
  do_sample: false
  enable_thinking: false
  max_tokens: 1024
  model_type: vllm
  name: Qwen/Qwen3-8B
  quantization: false
  system_prompt: Είστε ειδικός στην ανίχνευση παραπληροφόρησης και τον έλεγχο των
    γεγονότων. Ο στόχος σας είναι να προσδιορίσετε την κεντρική αξίωση στη δεδομένη
    θέση διατηρώντας παράλληλα την αρχική του γλώσσα.
  temperature: 0.0
prompt:
  prompt_type: prompt
  template: 'Είστε ειδικός στην ανίχνευση παραπληροφόρησης και τον έλεγχο των γεγονότων.
    Ο στόχος σας είναι να προσδιορίσετε την κεντρική αξίωση στη δεδομένη θέση διατηρώντας
    παράλληλα την αρχική του γλώσσα.


    Η κεντρική αξίωση πρέπει να πληροί τα ακόλουθα κριτήρια:

    - ** Επαληθεύσιμο **: Πρέπει να είναι ένας πραγματικός ισχυρισμός που μπορεί να
    ελεγχθεί κατά των αποδεικτικών στοιχείων.

    - ** Συνοπτική **: Θα πρέπει να είναι μια ενιαία, σαφής πρόταση που καταγράφει
    τον κύριο ισχυρισμό της θέσης.

    - ** Κοινωνικά επιζήμια **: Θα πρέπει να είναι μια δήλωση που θα μπορούσε να επηρεάσει
    την κοινή γνώμη, την υγεία ή την πολιτική.

    - ** Δωρεάν από ρητορικά στοιχεία **: Μην συμπεριλάβετε τις απόψεις, τις ρητορικές
    ερωτήσεις ή το περιττό πλαίσιο.

    - ** Διατήρηση της αρχικής γλώσσας **: Η έξοδος πρέπει να είναι στην ίδια γλώσσα
    με την ανάρτηση εισόδου.


    Εξάγετε μόνο την κεντρική αξίωση χωρίς πρόσθετη εξήγηση ή μορφοποίηση.


    Παραδείγματα: {examples}


    Δημοσίευση: {post}


    Κανονικοποιημένη αξίωση:'
