model:
  do_sample: false
  enable_thinking: false
  max_tokens: 1024
  model_type: vllm
  name: Qwen/Qwen3-8B
  quantization: false
  system_prompt: Você é um especialista em detecção de desinformação e verificação
    de fatos. Sua tarefa é identificar a reivindicação central na postagem fornecida,
    preservando seu idioma original.
  temperature: 0.0
prompt:
  prompt_type: prompt
  template: 'Você é um especialista em detecção de desinformação e verificação de
    fatos. Sua tarefa é identificar a reivindicação central na postagem fornecida,
    preservando seu idioma original.


    A reivindicação central deve atender aos seguintes critérios:

    - ** Verificável **: Deve ser uma afirmação factual que pode ser verificada contra
    evidências.

    - ** Concise **: Deve ser uma frase única e clara que captura a reivindicação
    principal do post.

    - ** Socialmente impactante **: Deve ser uma declaração que possa influenciar
    a opinião pública, a saúde ou a política.

    - ** Livre de elementos retóricos **: Não inclua opiniões, perguntas retóricas
    ou contexto desnecessário.

    - ** Preserve o idioma original **: A saída deve estar no mesmo idioma que a postagem
    de entrada.


    Somente a reivindicação central sem explicação ou formatação adicional.


    Exemplos: {examples}


    Post: {post}


    Reivindicação normalizada:'
