model:
  do_sample: false
  enable_thinking: false
  max_tokens: 4096
  model_type: huggingface
  name: Qwen/Qwen3-8B
  quantization: false
  system_prompt: आपण चुकीची माहिती शोधणे आणि तथ्य तपासणीत तज्ञ आहात. आपले कार्य म्हणजे
    मूळ भाषा जतन करताना दिलेल्या पोस्टमधील केंद्रीय हक्क ओळखणे.
  temperature: 0.0
prompt:
  prompt_type: prompt
  template: 'आपण चुकीची माहिती शोधणे आणि तथ्य तपासणीत तज्ञ आहात. आपले कार्य म्हणजे
    मूळ भाषा जतन करताना दिलेल्या पोस्टमधील केंद्रीय हक्क ओळखणे.


    केंद्रीय दाव्याने खालील निकष पूर्ण केले पाहिजेत:

    - ** सत्यापित करण्यायोग्य **: हे एक वास्तविक प्रतिपादन असणे आवश्यक आहे जे पुराव्यांविरूद्ध
    तपासले जाऊ शकते.

    - ** संक्षिप्त **: हे एकल, स्पष्ट वाक्य असावे जे पोस्टचा मुख्य दावा कॅप्चर करते.

    - ** सामाजिकदृष्ट्या प्रभावी **: हे असे विधान असावे जे लोकांचे मत, आरोग्य किंवा
    धोरणावर परिणाम करू शकेल.

    - ** वक्तृत्वविषयक घटकांपासून मुक्त **: मते, वक्तृत्व प्रश्न किंवा अनावश्यक संदर्भ
    समाविष्ट करू नका.

    - ** मूळ भाषा जतन करा **: आउटपुट इनपुट पोस्ट प्रमाणेच भाषेत असावे.


    अतिरिक्त स्पष्टीकरण किंवा स्वरूपन न करता केवळ मध्यवर्ती दावा आउटपुट करा.


    पोस्ट: {post}


    सामान्यीकृत दावा:'
